/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.13/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "buildLogic"

include("plugin")

pluginManagement {
    repositories {
        if (settings.extra.get("useAR") == "true") {
            maven { url = uri("artifactregistry://us-maven.pkg.dev/PROJECT_ID/REPOSITORY_ID") }
        } else {
            gradlePluginPortal()
        }
    }
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.9.0"
}

dependencyResolutionManagement {
    repositories {
        if (settings.extra.get("useAR") == "true") {
            maven { url = uri("artifactregistry://us-maven.pkg.dev/PROJECT_ID/REPOSITORY_ID") }
        } else {
            mavenCentral()
            gradlePluginPortal()
        }
    }
}
