/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import com.ncorti.ktfmt.gradle.KtfmtExtension
import com.ncorti.ktfmt.gradle.KtfmtPlugin
import org.gradle.api.Plugin
import org.gradle.api.Project

/** A simple 'hello world' plugin. */
class BuildLogicPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        println("Applying ktfmt")
        // Apply the Ktfmt plugin to the project and set the style properly
        project.plugins.apply(KtfmtPlugin::class.java)
        project.extensions.getByType(KtfmtExtension::class.java).apply { kotlinLangStyle() }

        // Register a task
        project.tasks.register("greeting") { task ->
            task.doLast { println("Hello from the buildLogic plugin") }
        }
    }
}
