/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/8.13/userguide/custom_plugins.html in the Gradle documentation.
 */

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`

    // Apply the Kotlin JVM plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
}
java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }

dependencies {
    implementation("com.ncorti.ktfmt.gradle:com.ncorti.ktfmt.gradle.gradle.plugin:+")
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

gradlePlugin {
    // Define the plugin
    val greeting by
        plugins.creating {
            id = "org.example.applyKtFmt"
            implementationClass = "org.example.BuildLogicPlugin"
        }
}
